tasks:
  - init: |
      docker run -d -p 8443:8443 -v /workspace:/config/workspace astrabert/bigdata-rstudio-rocker:latest

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8443
    onOpen: open-browser
